# Generated by Django 3.2.6 on 2021-11-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HILs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='hostname')),
                ('station', models.CharField(max_length=10, verbose_name='station')),
                ('responsible', models.CharField(max_length=10, verbose_name='responsible name')),
            ],
        ),
    ]
