# Generated by Django 3.2.6 on 2021-11-03 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table_view', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HILs',
        ),
    ]
